# Generated by Django 4.1.7 on 2023-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('category', models.CharField(choices=[('OTHER', 'Other'), ('CPU', 'CPU'), ('GPU', 'GPU'), ('MONITOR', 'Monitor'), ('MOTHERBOARD', 'Motherboard')], default='OTHER', max_length=20, verbose_name='Category')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
