# Generated by Django 4.1.7 on 2023-02-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('MONITOR', 'Monitor'), ('MOTHERBOARD', 'Motherboard')], default='OTHER', max_length=20, verbose_name='Category'),
        ),
    ]
