# Generated by Django 4.1.7 on 2023-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('MONITOR', 'Monitor'), ('MOTHERBOARD', 'Motherboard'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category'),
        ),
    ]
